apiVersion: v1 
kind: Namespace
metadata:
  name: dev3
--- 
apiVersion: v1 
kind: LimitRange
metadata:
  name: default-cpu-mem-limit-range
  namespace: dev3
spec: 
  limits:
    - default:
        cpu: "500m"      # default value = 1 vCPU
        memory: "512Mi"  #default value = 512Mi
      defaultRequest:
        cpu: "300m"
        memory: "256Mi"
      type: Container