apiVersion: v1 
kind: Service
metadata:
  name: frontend-nginxapp-nodeport-svc
  labels:
    app: frontend-nginxapp
    tier: frontend
spec:
  type: NodePort
  selector:
    app: frontend-nginxapp
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31234
#http://node-port:31234/hello