apiVersion: v1
kind: Service
metadata:
  name: myapp-pod-nodeport-svc
spec:
  type: NodePort 
  selector: 
    app: myapp-pod
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31231